CrickAuction/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('players/',include('players.urls')),
    path('auctioneer/',include('auctioneer.urls')),
    path('franchise/',include('franchise.urls')),
    path('logout/',views.user_logout,name='logout'),
]

auctioneer/urls.py
from django.urls import path
from . import views

app_name = 'auctioneer'

urlpatterns = [
    path('login/',views.login,name='auctioneer_login'),
    path('index/',views.index,name="auctioneer_index"),
    path('live_auction/<str:auc_name>',views.live_auction,name="live_auction"),
    path('add/<str:auc_name>',views.add,name="add"),
    path('auction/<str:auc_name>',views.auction,name="auction"),
]

franchise/urls.py
from django.urls import path
from . import views

app_name = 'franchise'

urlpatterns = [
    path('login/',views.login,name='franchise_login'),
    path('register/',views.register,name='franchise_register'),
    path('dashboard/',views.dashboard,name='franchise_dashboard'),
    path('bid/<str:player_email>',views.bid,name='bid'),
    path('dashboard1/',views.dashboard1,name='dashboard1'),
    path('report/',views.report,name = 'report'),
]

players/urls.py
from django.urls import path
from . import views

app_name = 'players'

urlpatterns = [
    path('login/',views.login,name='player_login'),
    path('register/',views.register,name='player_register'),
    path('dashboard/',views.dashboard,name='player_dashboard'),
]

CrickAuction/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import logout

def index(request):
    return render(request,'index.html')
    #return HttpResponse("hello, welcome to index page")

def user_logout(request):
    logout(request)
    return render(request,'index.html')

CrickAuction/templates/index.html
{% extends 'layout.html' %}

{% block title %}
    home
{% endblock %}

{% block main %}
    <style>
      #small {
                color: #ff652f; /* Change to your desired color */
            }
    </style>
    <img src="CrickAuction/auctionbg.jpg" alt="auction background " width="500" height="300">
    <h1 id="small">Ready to compete?</h1>

    <button type="button" class="btn btn-outline-primary btn-lg">Roles</button>
    <p>

    </p>
   <!-- <a href=""><img src="static/auctioneer.jpg" class="img-rounded" alt="auctioneer" width="300" height="400"></a>
    <a href="players/login"><img src="static/player.jpeg"  alt="player" width="300" height="400"></a>
    <a href=""><img src="static/franchise.jpg"  alt="franchise" width="300" height="400"></a> -->

    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="thumbnail with-border">
            <a href="{% url 'auctioneer:auctioneer_login' %}" target="_blank">
              <img src="static/auctioneer.jpg" alt="Auctioneer" width="300" height="400">
              <div class="caption">
                <p><h3>Auctioneer</h3></p>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <div class="thumbnail with-border">
            <a href="{% url 'players:player_login' %}" target="_blank">
              <img src="static/player.jpeg" alt="Player" width="300" height="400">
              <div class="caption">
                <p><h3>Player</h3></p>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <div class="thumbnail with-border">
            <a href="{% url 'franchise:franchise_login' %}" target="_blank">
              <img src="static/franchise.jpg" alt="Franchise" width="300" height="400">
              <div class="caption">
                <p><h3>Franchise</h3></p>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>



{% endblock %}

CrickAuction/templates/layout.html
<!DOCTYPE html>

<html lang="en">

    <head >

        <meta charset="utf-8">
        <meta name="viewport" content="initial-scale=1, width=device-width">

        <!-- http://getbootstrap.com/docs/5.3/ -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

        <!-- https://favicon.io/emoji-favicons/money-bag/ -->
        <link href="/static/logo.jpeg" rel="icon">

        <link href="/static/styles.css" rel="stylesheet">

        <style>
            #head {
                color: #14a76c; /* Change to your desired color */
            }
            .navbar-custom {
            background-color: #272727; /* Replace with your desired color */
            }
    
            /* Customize other header text colors */
            .navbar-nav .nav-link {
                color: #14a76c; /* Change to your desired color */
                font-weight: bold;
            }
            /* Optional: Add hover effect for nav-links */
            .navbar-nav .nav-link:hover {
                color: #fcfcfc; /* Change to your desired hover color */
            }
            .bgimg {
            background-image: url('/static/.jpg'); /* Update the path as needed */
            background-size: cover; /* Ensures the image covers the entire element */
            background-position: center; /* Centers the image */
            background-repeat: no-repeat; /* Prevents the image from repeating */
            height: 100vh; /* Sets the height to 100% of the viewport height */
            width: 100%; /* Sets the width to 100% */
            }
            body {
            background-color: #747474; /* Replace with your desired color */
            }
        </style>
    

        <title>IPL Auction: {% block title %}{% endblock %}</title>

    </head>

    <body>
        <div>
            <nav class="navbar-custom border navbar navbar-expand-md fixed-top">
                <div class="container-fluid" >
                    <h1 id="head"><i>IPL</i> Auction</h1>
                    <!--<a class="navbar-brand" href="/"><span class="blue">I</span><span class="red"></span><span class="yellow">P</span><span class="green">L</span> <span class="red"> Auction</span></a> -->
                    <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-bs-target="#navbar" data-bs-toggle="collapse" type="button">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>

                
    
                <div class="collapse navbar-collapse" id="navbar-nav">
                    <ul id="head" class="navbar-nav ml-auto">
                      <li class="nav-item">
                        <a class="nav-link  h6"  href="{% url 'index' %}">Login</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link  h6"  href="#about">About</a>
                      </li>
                      <li  class="nav-item ">
                        <a class="nav-link  h6"  href="{% url 'logout' %}">Logout</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link  h6" href="#team"></a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link text-white h6" href="#contact"></a>
                      </li>
                    </ul>
                  </div>

                  <div id="head">
                    {% if user.is_authenticated %}
                        Signed in as <strong>{{ user.username }}</strong>.
                    {% else %}
                        Not signed in.
                    {% endif %}
                </div>
            </nav>

            

            <main class="container py-5 text-center">
                <p>




                </p>
                <p>



                </p>
                {% block main %}{% endblock %}
            </main>

            <footer class="mb-5">

                

            
                <!-- <script>
                    document.addEventListener('DOMContentLoaded', function() {
                        // Adapted from https://stackoverflow.com/a/10162353
                        const html = '<!DOCTYPE ' +
                        document.doctype.name +
                        (document.doctype.publicId ? ' PUBLIC "' + document.doctype.publicId + '"' : '') +
                        (!document.doctype.publicId && document.doctype.systemId ? ' SYSTEM' : '') +
                        (document.doctype.systemId ? ' "' + document.doctype.systemId + '"' : '') +
                        '>\n' + document.documentElement.outerHTML;
                        document.querySelector('form[action="https://validator.w3.org/check"] > input[name="fragment"]').value = html;
                    });
                </script> -->
            </footer>

        </div>

    </body>

</html>