CrickAuction/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('players/',include('players.urls')),
    path('auctioneer/',include('auctioneer.urls')),
    path('franchise/',include('franchise.urls')),
    path('logout/',views.user_logout,name='logout'),
]

auctioneer/urls.py
from django.urls import path
from . import views

app_name = 'auctioneer'

urlpatterns = [
    path('login/',views.login,name='auctioneer_login'),
    path('index/',views.index,name="auctioneer_index"),
    path('live_auction/<str:auc_name>',views.live_auction,name="live_auction"),
    path('add/<str:auc_name>',views.add,name="add"),
    path('auction/<str:auc_name>',views.auction,name="auction"),
]

franchise/urls.py
from django.urls import path
from . import views

app_name = 'franchise'

urlpatterns = [
    path('login/',views.login,name='franchise_login'),
    path('register/',views.register,name='franchise_register'),
    path('dashboard/',views.dashboard,name='franchise_dashboard'),
    path('bid/<str:player_email>',views.bid,name='bid'),
    path('dashboard1/',views.dashboard1,name='dashboard1'),
    path('report/',views.report,name = 'report'),
]

players/urls.py
from django.urls import path
from . import views

app_name = 'players'

urlpatterns = [
    path('login/',views.login,name='player_login'),
    path('register/',views.register,name='player_register'),
    path('dashboard/',views.dashboard,name='player_dashboard'),
]

franchise/models.py
# franchise/models.py

from django.contrib.auth.models import User
from django.db import models

class FranchiseProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #email = models.EmailField(unique=True)
    liscence = models.CharField(max_length=50, unique=True)
    purse_money = models.DecimalField(max_digits=20,decimal_places=2,default=0.00,null=True)
    def __str__(self):
        return self.user.username

franchise/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User, Group
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.decorators import login_required
from .models import FranchiseProfile
from players.models import PlayerProfile
from django.shortcuts import render, get_object_or_404
from auctioneer.models import *
import datetime
from pytz import UTC
    # Create your views here.
def login(request):
        if request.method == 'POST':
            username = request.POST.get('username', '')
            password = request.POST.get('password', '')
            user = authenticate(request,username=username,password=password)

            if user is not None:
                if user.groups.filter(name='franchise').exists():
                    auth_login(request,user)
                    messages.success(request,"login successfull")
                    return redirect('franchise:dashboard1')
                else:
                    messages.warning(request,"login with franchise credentials")
            

        return render(request,'franchise_login.html')

def register(request):
        if request.method == 'POST':
            username = request.POST['username']
            email = request.POST['email']
            lisence = request.POST['liscence']
            password = request.POST['password']
            confpassword = request.POST['confpassword']

            if password != confpassword:
                messages.error(request,"password and confirmation doesn't match")
                return redirect('franchise:franchise_register')
            
            if User.objects.filter(email=email).exists():
                messages.error(request, "Email already in use in User model.")
                return redirect('franchise:franchise_register')
            
            user = User.objects.create_user(username=username, email=email, password=password)

            franchise_object = FranchiseProfile.objects.create(user=user,liscence=lisence)

            franchise_group = Group.objects.get(name='franchise')
            user.groups.add(franchise_group)
            
            messages.success(request, "Registration successful.")
            return redirect('franchise:franchise_login')

            
        return render(request,'franchise_register.html')

def dashboard(request):
        players = list(PlayerProfile.objects.all())
        return render(request,'franchise_dashboard.html',{'players':players })

@login_required
def bid(request,player_email):
        player = get_object_or_404(PlayerProfile, user__email=player_email)
        franchise1 = get_object_or_404(FranchiseProfile, user = request.user)


        if request.method == 'POST':
            user = request.user
            if user.groups.filter(name='franchise').exists():

                bid = int(request.POST['bid']) 
                if player.current_bid is None and bid >= player.base_price and bid <= franchise1.purse_money :
                    player.current_bid = bid
                    player.current_team = request.user.username
                    player.save()
                    messages.success(request,"bid successfull")
                    return redirect('franchise:franchise_dashboard')


                elif(bid > player.current_bid and bid <= franchise1.purse_money):
                    last_bid = player.current_bid
                    last_team = player.current_team
                    franchise = get_object_or_404(FranchiseProfile, user__username = last_team)
                    franchise.purse_money = franchise.purse_money + last_bid
                    franchise.save()
                    player.current_bid = bid
                    player.current_team = request.user.username
                    player.save()
                    franchise1.purse_money = franchise1.purse_money - bid
                    franchise1.save()
                    messages.success(request,"bid successfull")
                    return redirect('franchise:franchise_dashboard')

                
                else:
                    messages.warning(request,"bid failed")
            
            else:
                messages.warning(request,"you don't have access")
                
                return redirect('franchise:franchise_dashboard')
        return render(request,'bid.html',{'player_data':player})

@login_required
def dashboard1(request):
        franchise_user = request.user
        franchise_data = get_object_or_404(FranchiseProfile, user=franchise_user)
        players = list(PlayerProfile.objects.filter(current_team = franchise_user.username))
        auctions = list(LiveAuction.objects.filter(scheduled_time__gt = datetime.datetime.now().replace(tzinfo=UTC)))
        context = {
            'players': players,
            'franchise': franchise_data,
            'auctions': auctions
        }
        return render(request,'dashboard.html',context)

@login_required
def report(request):
        franchises = FranchiseProfile.objects.all()
        franchise_data = []

        for franchise in franchises:
            players = list(PlayerProfile.objects.filter(current_team = franchise.user.username))
            franchise_data.append({
                'franchise':franchise,
                'players':players
            })

        return render(request,'report.html',{'franchise_data':franchise_data})

franchise/templates/bid.html
{% extends 'layout.html' %}

{% block title %}
    player login
{% endblock %}

{% block main %}
<style>
    body{
        background:#747474;
        text-decoration-color:#ff652f ;
    }
    #small {
                color: #ff652f;
                /*color:#14a76c*/
            }
</style>

{% if messages %}
        <div class="alert alert-info">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
<div class="container rounded  mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px" src="https://c8.alamy.com/comp/2GPKNRJ/cricket-player-icon-2GPKNRJ.jpg"><span id="small" class="font-weight-bold">{{player_data.user.first_name}} {{ player_data.user.last_name }}</span><span id="small" >{{player_data.user.email}}</span><span> </span></div>
        </div>
        <div class="col-md-5 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Profile Status</h4>
                </div>
                <div class="row mt-2">
                    <div class="col-md-6"><label class="labels">Name</label><h3 id="small">{{ player_data.user.first_name }}</h3></div>
                    <div class="col-md-6"><label class="labels">Surname</label><h3 id="small">{{ player_data.user.last_name }}</h3></div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12"><label class="labels">Native</label><h3 id="small">{{ player_data.native }}</h3></div>
                    <div class="col-md-12"><label class="labels">Role</label><h3 id="small">{{ player_data.role }}</h3></div>
                    <div class="col-md-12"><label class="labels">Base Price</label><h3 id="small">Rs.{{ player_data.base_price }}</h3></div>
                </div>
                
                <div class="row mt-3">
                    <div class="col-md-6"><label class="labels">Current Team</label><h3 id="small">{{ player_data.current_team }}</h3></div>
                    <div class="col-md-6"><label class="labels">Current Bid</label><h3 id="small">Rs.{{ player_data.current_bid }}</h3></div>
                </div>
                <form action="{% url 'franchise:bid' player_data.user.email %}" method="POST">
                    {% csrf_token %}
                <div class="row mt-3">
                    <div class="col-md-6"><input type="number" class="form-control" placeholder="Place bid" name="bid"></div>
                    <div class="col-md-6"><button type="submit" class="btn btn-info">Bid</button>
                    </div>
                </div>
                </form>
            </div>
        </div>      
        <div class="col-md-4">
            <div class="row mt-2">
                <p><br><br><br></p>
                <div class="col-md-6"><label class="labels">Batting Style</label><h3 id="small">{{ player_data.batting_style }}</h3></div><br>
                    <div class="col-md-6"><label class="labels">Bowling Style</label><h3 id="small">{{ player_data.bowling_style }}</h3></div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

franchise/templates/dashboard.html
{% extends 'layout.html' %}
{% block title %}
    franchise dashboard
{% endblock %}

{% block main %}
<style>
    .col-md-4:hover{
        opacity: 0.7;
    }
</style>
<head>
    <meta charset="utf-8">
    <title>top customers list - Bootdey.com</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
        body {
            margin-top: 20px;
            background: #747474;
        }
        .card {
            box-shadow: 0 20px 27px 0 rgb(0 0 0 / 5%);
        }
        
        a {
            text-decoration: none;    
        }
        .avatar-text {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        background: #000;
        color: #fff;
        font-weight: 700;
    }

    .avatar {
        width: 3rem;
        height: 3rem;
    }
    .rounded-3 {
        border-radius: 0.5rem!important;
    }
    .mb-2 {
        margin-bottom: 0.5rem!important;
    }
    .me-4 {
        margin-right: 1.5rem!important;
    }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <!-- Column 1: Top Customers Card -->
        <div class="col-md-6 mb-3 mb-lg-5">
            <div class="card">
                <div class="d-flex card-header justify-content-between">
                    <h5 class="me-3 mb-0">Current players</h5>
                    
                </div>
                {% for player in players %}
                    <div class="card-body">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item pt-0">
                                <div class="d-flex align-items-center">
                                    <div class="flex-shrink-0 me-3">                                   
                                        <img src="https://c8.alamy.com/comp/2GPKNRJ/cricket-player-icon-2GPKNRJ.jpg" alt class="avatar rounded-circle">
                                        <!--<span class="avatar avatar-text rounded-3 me-4 mb-2">{{ player.user.first_name }}</span>-->
                                    </div>
                                    <div class="flex-grow-1">
                                        <h6 class="mb-0">{{ player.user.first_name }} {{ player.user.last_name }}</h6>
                                        <p class="mb-0 text-muted">{{player.batting_style}} batter, {{player.bowling_style}} bowler</p>
                                    </div>
                                    <div class="flex-shrink-0 text-end">
                                        <span>Rs.{{player.current_bid}}</span>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                {% endfor %}
            </div>
        </div>
        <!-- Column 2: Profile Card -->
        <div class="col-md-6 mt-4 mb-4 p-3 d-flex justify-content-center">
            <div class="card p-4">
                <div class="image d-flex flex-column justify-content-center align-items-center">
                    <!--<button class="btn btn-secondary"> -->
                        <!--<img src="https://i.imgur.com/wvxPV9S.png" height="100" width="100" />-->
                        <span class="avatar avatar-text rounded-3 me-4 mb-2">{{franchise.user}}</span>

                    <!--</button>-->
                    <span class="name mt-3">{{franchise.user.email}}</span> 
                    
                    <div class="d-flex flex-row justify-content-center align-items-center mt-3"> 
                        <span class="number">Rs. {{franchise.purse_money}}<span class="follow">   Balance purse</span></span> 
                    </div> 
                    <p>
                        <br>
                    </p>
                    <div>
                        <a href="{% url 'franchise:franchise_dashboard' %}" class="btn btn-info stretched-link">Bid for players</a>
                    </div>
                    
                    
                    <div class="gap-3 mt-3 icons d-flex flex-row justify-content-center align-items-center"> 
                        <span><i class="fa fa-twitter"></i></span> 
                        <span><i class="fa fa-facebook-f"></i></span> 
                        <span><i class="fa fa-instagram"></i></span> 
                        <span><i class="fa fa-linkedin"></i></span> 
                    </div> 
                    
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <a href="{% url 'franchise:report' %}" class="btn btn-warning ">Auction Report</a>
</div>
<br><br>
<h1 class="text-center text-light">Upcomming Live Auctions</h1>
<br><br>
<div class="row m-1">
    {% for auction in auctions %}
        <div class="col-md-4 mb-4">
            <div class="card bg-dark text-light h-100" onclick="location.href='{% url 'auctioneer:auction' auction.name %}';">
                <div class="card-body">
                    <h5 class="card-title">{{auction.name}}</h5>
                    <p class="card-text">Starts {{auction.scheduled_time}}</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
{% endblock %}

franchise/templates/franchise_dashboard.html
{% extends 'layout.html' %}
{% block title %}
    franchise dashboard
{% endblock %}

{% block main %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
            body{
        background:#747474;
    }

    .card {
        box-shadow: 0 20px 27px 0 rgb(0 0 0 / 5%);
    }

    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 0 solid rgba(0,0,0,.125);
        border-radius: 1rem;
    }

    .card-body {
        -webkit-box-flex: 1;
        -ms-flex: 1 1 auto;
        flex: 1 1 auto;
        padding: 1.5rem 1.5rem;
    }
    .avatar-text {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        background: #000;
        color: #fff;
        font-weight: 700;
    }

    .avatar {
        width: 3rem;
        height: 3rem;
    }
    .rounded-3 {
        border-radius: 0.5rem!important;
    }
    .mb-2 {
        margin-bottom: 0.5rem!important;
    }
    .me-4 {
        margin-right: 1.5rem!important;
    }
    #small {
                color: #ff652f; /* Change to your desired color */
            }
        </style>
    </head>
    <body>
    {% if messages %}
        <div class="alert alert-info">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <div class="container">
    <div class="text-center mb-5">
        <h3 id="small"><br>Bid for Players</h3>
    <p class="lead"></p>
    </div>
    {% for player in players %}
        <div class="card mb-3">
            <div class="card-body">
                <div class="d-flex flex-column flex-lg-row">
                <span class="avatar avatar-text rounded-3 me-4 mb-2">{{ player.user.first_name }}</span>
                    <div class="row flex-fill">
                        <div class="col-sm-5">
                        <h4 class="h5">{{ player.user.first_name }} {{ player.user.last_name }}</h4>
                        <span class="badge bg-secondary">{{ player.native }}</span> 
                        {% if player.current_team is none %}
                            <span class="badge bg-success">Base Price<br>Rs.{{ player.base_price }}</span>
                        {% else %}
                            <span class="badge bg-success">{{player.current_team}} <br>Rs.{{player.current_bid}}</span>
                        {% endif %}
                        </div>
                        <div class="col-sm-4 py-2">
                        <span class="badge bg-info">{{ player.batting_style }}<br> batter</span>
                        <span class="badge bg-danger">{{ player.bowling_style }}<br> bowler</span>
                        <span class="badge bg-secondary"></span>
                        <span class="badge bg-secondary"></span>
                        </div>
                        <div class="col-sm-3 text-lg-end">
                        <a href="{% url 'franchise:bid' player.user.email %}" class="btn btn-primary stretched-link">Bid</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    
    <div>
        <a href="{% url 'franchise:dashboard1'  %}" class="btn btn-warning ">Current Team Status</a>
    </div>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript">
        
    </script>
    </body>
{% endblock %}

franchise/templates/franchise_login.html
{% extends 'layout.html' %}

{% block title %}
    franchise login
{% endblock %}

{% block main %}
{% if messages %}
        <div class="alert alert-info">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
{% endif %}
    
    <img src="">
        
    
    <form action="{% url 'franchise:franchise_login' %}" method="POST" autocomplete="off" >
        {% csrf_token %}

        <input autocomplete="false" name="username" type="text"  size="30" class="form-control mb-2 mr-sm-2 " placeholder="Franchise Username" autofocus>
        <p>

        </p>
        <input type="password" name="password" size="50" class="form-control mb-2 mr-sm-2 " placeholder="Password">
        <button type="submit" class="btn btn-info">Login</button>
    </form>
    <p>

    </p>
    <a href="{% url 'franchise:franchise_register' %}">Not registered?</a>


{% endblock %}

franchise/templates/franchise_register.html
{% extends 'layout.html' %}

{% block title %}
    franchise login
{% endblock %}

{% block main %}
{% if messages %}
        <div class="alert alert-info">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
{% endif %}
    
    <img src="">
        
    
    <form action="{% url 'franchise:franchise_register' %}" method="POST" autocomplete="off" >
        {% csrf_token %}
        <input autocomplete="false" name="username" type="text"  size="30" class="form-control mb-2 mr-sm-2" placeholder="Franchise name" autofocus>
        <p>

        </p>
        <input type="email" name="email" class="form-control mb-2 mr-sm-2" placeholder="Email ID">
        <input type="text" name="liscence" class="form-control mb-2 mr-sm-2" placeholder="liscence ID number">
        <input type="password" name="password" size="50" class="form-control mb-2 mr-sm-2" placeholder="Create Password">
        <input type="password" name="confpassword" class="form-control mb-2 mr-sm-2" placeholder="Confirm password">
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
    <p>

    </p>


{% endblock %}

franchise/templates/report.html
{% extends 'layout.html' %}
{% block title %}
    franchise dashboard
{% endblock %}

{% block main %}


<head>
<meta charset="utf-8">


<title>Clients - Bootdey.com</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" rel="stylesheet">
<style type="text/css">
    	body{margin-top:20px;
background-color: #747474;
}

.timeline {
    list-style-type: none;
    position: relative
}

.timeline:before {
    background: #dee2e6;
    left: 9px;
    width: 2px;
    height: 100%
}

.timeline-item:before,
.timeline:before {
    content: " ";
    display: inline-block;
    position: absolute;
    z-index: 1
}

.timeline-item:before {
    background: #fff;
    border-radius: 50%;
    border: 3px solid #3b7ddd;
    left: 0;
    width: 20px;
    height: 20px
}
.card {
    margin-bottom: 24px;
    box-shadow: 0 0 0.875rem 0 rgba(33,37,41,.05);
}
.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: initial;
    border: 0 solid transparent;
    border-radius: .25rem;
}
.card-body {
    flex: 1 1 auto;
    padding: 1.25rem;
}
.card-header:first-child {
    border-radius: .25rem .25rem 0 0;
}
.card-header {
    border-bottom-width: 1px;
}
.pb-0 {
    padding-bottom: 0!important;
}
.card-header {
    padding: 1rem 1.25rem;
    margin-bottom: 0;
    background-color: #fff;
    border-bottom: 0 solid transparent;
}
    </style>
</head>
<body>
<div class="container">
<div class="container-fluid p-0">
<h1 class="h3 mb-3">Auction Report</h1>
<div class="row">

{% for data in franchise_data %}
<div class="card">
    <div class="card-header pb-0">
        <div class="card-actions float-right">
            <div class="dropdown show">
            <a href="#" data-toggle="dropdown" data-display="static">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal align-middle"><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle></svg>
            </a>
                <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </div>
        </div>
    <h5 class="card-title mb-0">{{data.franchise.user}}</h5>
    </div>
    <div class="card-body">
        <table class="table table-striped" style="width:100%">
                <thead>
                    <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Role</th>
                    <th>Email</th>
                    <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for player in data.players %}
                        <tr>
                        <td><img src="https://bootdey.com/img/Content/avatar/avatar1.png" width="32" height="32" class="rounded-circle my-n1" alt="Avatar"></td>
                        <td>{{player.user.first_name}} {{player.user.last_name}}</td>
                        <td>{{player.role}}</td>
                        <td><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="8beceaf9f9eeffffcbfce2e5ffeef9f8a5e8e4e6">{{player.user.email}}</a></td>
                        <td><span class="badge bg-success">Active</span></td>
                        </tr>
                    {% endfor %}
                </tbody>
        </table>
    </div>
</div>
</div>
{% endfor %}
<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript">
	
</script>
</body>
</html>

{% endblock %}